/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.dao.EspecialidadeDAO;
import java.awt.Toolkit;

/**
 *
 * @author 22282790
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/senai/sp/jandira/imagens/notebook.png")));
        initPanels();
        
    }

    //Atributos da classe
    PanelEspecialidades panelEspecialidades;

    //Constantes
    private final int POS_X = 10;
    private final int POS_Y = 190;
    private final int LARGURA = 890;
    private final int ALTURA = 430;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelSistemaDeAgendamentosDeConsultas = new javax.swing.JLabel();
        buttonAgenda = new javax.swing.JButton();
        buttonPacientes = new javax.swing.JButton();
        buttonMedicos = new javax.swing.JButton();
        buttonEspecialidades = new javax.swing.JButton();
        buttonPlanosDeSaude = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();
        panelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        buttonHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Agendamentos");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        labelSistemaDeAgendamentosDeConsultas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelSistemaDeAgendamentosDeConsultas.setForeground(new java.awt.Color(204, 0, 204));
        labelSistemaDeAgendamentosDeConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/timetable.png"))); // NOI18N
        labelSistemaDeAgendamentosDeConsultas.setText("Sistema de Agendamento de Consultas");
        jPanel1.add(labelSistemaDeAgendamentosDeConsultas);
        labelSistemaDeAgendamentosDeConsultas.setBounds(20, 20, 650, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 920, 90);

        buttonAgenda.setBackground(new java.awt.Color(204, 204, 204));
        buttonAgenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonAgenda.setForeground(new java.awt.Color(255, 0, 51));
        buttonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/notebook.png"))); // NOI18N
        buttonAgenda.setToolTipText("Agenda");
        getContentPane().add(buttonAgenda);
        buttonAgenda.setBounds(140, 120, 50, 40);

        buttonPacientes.setBackground(new java.awt.Color(204, 204, 204));
        buttonPacientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonPacientes.setForeground(new java.awt.Color(255, 0, 51));
        buttonPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/fever.png"))); // NOI18N
        buttonPacientes.setToolTipText("Pacientes");
        getContentPane().add(buttonPacientes);
        buttonPacientes.setBounds(210, 120, 50, 40);

        buttonMedicos.setBackground(new java.awt.Color(204, 204, 204));
        buttonMedicos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonMedicos.setForeground(new java.awt.Color(255, 0, 51));
        buttonMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/doctor.png"))); // NOI18N
        buttonMedicos.setToolTipText("Médicos");
        buttonMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMedicosActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMedicos);
        buttonMedicos.setBounds(280, 120, 50, 40);

        buttonEspecialidades.setBackground(new java.awt.Color(204, 204, 204));
        buttonEspecialidades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonEspecialidades.setForeground(new java.awt.Color(255, 0, 51));
        buttonEspecialidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/recompensa.png"))); // NOI18N
        buttonEspecialidades.setToolTipText("Especialidades");
        buttonEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEspecialidadesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEspecialidades);
        buttonEspecialidades.setBounds(350, 120, 50, 40);

        buttonPlanosDeSaude.setBackground(new java.awt.Color(204, 204, 204));
        buttonPlanosDeSaude.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonPlanosDeSaude.setForeground(new java.awt.Color(255, 0, 0));
        buttonPlanosDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/planoDeSaude.png"))); // NOI18N
        buttonPlanosDeSaude.setToolTipText("Planos de Saúde");
        getContentPane().add(buttonPlanosDeSaude);
        buttonPlanosDeSaude.setBounds(420, 120, 50, 40);

        buttonSair.setBackground(new java.awt.Color(255, 0, 51));
        buttonSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonSair.setForeground(new java.awt.Color(255, 255, 255));
        buttonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/logout.png"))); // NOI18N
        buttonSair.setText("Sair");
        buttonSair.setToolTipText("Sair");
        getContentPane().add(buttonSair);
        buttonSair.setBounds(800, 100, 100, 80);

        panelHome.setBackground(new java.awt.Color(255, 255, 255));
        panelHome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelHome.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("SISACON");
        panelHome.add(jLabel1);
        jLabel1.setBounds(50, 90, 190, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Sistema de Agendamento de Consultas");
        panelHome.add(jLabel2);
        jLabel2.setBounds(50, 120, 330, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("Dados para contato:");
        panelHome.add(jLabel3);
        jLabel3.setBounds(60, 240, 170, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("e-mail: felipinhograciano@gmail.com");
        panelHome.add(jLabel4);
        jLabel4.setBounds(60, 270, 230, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telefone: (11)965853689");
        panelHome.add(jLabel5);
        jLabel5.setBounds(60, 300, 160, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Web Site: www.sisacon.com.br");
        panelHome.add(jLabel6);
        jLabel6.setBounds(60, 330, 200, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("SEJA BEM VINDO AO");
        panelHome.add(jLabel7);
        jLabel7.setBounds(270, 10, 350, 40);

        jTextField1.setBackground(new java.awt.Color(204, 0, 153));
        jTextField1.setBorder(null);
        jTextField1.setMinimumSize(new java.awt.Dimension(64, 5));
        jTextField1.setPreferredSize(new java.awt.Dimension(64, 5));
        panelHome.add(jTextField1);
        jTextField1.setBounds(50, 145, 820, 5);

        getContentPane().add(panelHome);
        panelHome.setBounds(10, 190, 890, 430);

        buttonHome.setBackground(new java.awt.Color(255, 255, 255));
        buttonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/home32.png"))); // NOI18N
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });
        getContentPane().add(buttonHome);
        buttonHome.setBounds(40, 120, 60, 50);

        setSize(new java.awt.Dimension(936, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMedicosActionPerformed

    private void buttonEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEspecialidadesActionPerformed

        panelHome.setVisible(false);
        panelEspecialidades.setVisible(true);
    }//GEN-LAST:event_buttonEspecialidadesActionPerformed

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        panelHome.setVisible(true);
        panelEspecialidades.setVisible(false);
    }//GEN-LAST:event_buttonHomeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgenda;
    private javax.swing.JButton buttonEspecialidades;
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonMedicos;
    private javax.swing.JButton buttonPacientes;
    private javax.swing.JButton buttonPlanosDeSaude;
    private javax.swing.JButton buttonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelSistemaDeAgendamentosDeConsultas;
    private javax.swing.JPanel panelHome;
    // End of variables declaration//GEN-END:variables

    private void initPanels() {

        panelEspecialidades = new PanelEspecialidades();
        panelEspecialidades.setBounds(POS_X,
                POS_Y,
                LARGURA,
                ALTURA);
        getContentPane().add(panelEspecialidades);
        panelEspecialidades.setVisible(false);

    }

}
